# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='coordinate_type',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
