# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_biologist',
            field=models.BooleanField(default=True, verbose_name='teacher status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
        migrations.AddField(
            model_name='user',
            name='patients',
            field=models.ManyToManyField(to='app.Patient'),
        ),
    ]
