# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='precision',
            field=models.FloatField(default=0.5723),
            preserve_default=False,
        ),
    ]
