# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180705_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
