# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_patient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='hgvs',
        ),
    ]
