# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180630_2306'),
        ('app', '0002_pathology_precision'),
    ]

    operations = [
    ]
