# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180525_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_id', models.CharField(max_length=30)),
                ('after', models.IntegerField(null=True)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('sequence', models.CharField(max_length=1000)),
                ('operation', models.CharField(choices=[('ins', 'Insertion'), ('del', 'Deletion'), ('insdel', 'Insertion-Deletion'), ('sub', 'Substitution'), ('dup', 'Duplication')], max_length=10)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
