# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20180705_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathology',
            old_name='precision',
            new_name='model_precision',
        ),
    ]
