# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_variation_hgvs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='seq_id',
            new_name='acc_id',
        ),
    ]
