# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180705_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='genotype',
            field=models.CharField(choices=[('homozyg', 'Homozygous'), ('heterocyg', 'Heterozygous'), ('homocyg-ref', 'Homozygous reference')], default='homozyg', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='coordinate_type',
            field=models.CharField(default='g', max_length=1),
        ),
    ]
