# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180708_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default='1990-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sample_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
