# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180525_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
            preserve_default=False,
        ),
    ]
