# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180709_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
