# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180527_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='source',
            field=models.CharField(default='manual', max_length=30),
        ),
    ]
