# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_annotation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
