# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180709_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathology',
            old_name='model_precision',
            new_name='model_precision_negative',
        ),
        migrations.RenameField(
            model_name='variationlocation',
            old_name='seq_id',
            new_name='acc_id',
        ),
        migrations.RemoveField(
            model_name='variationlocation',
            name='source',
        ),
        migrations.AddField(
            model_name='pathology',
            name='model_precision_positive',
            field=models.FloatField(default=0.6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationlocation',
            name='header_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='genotype',
            field=models.CharField(choices=[('homozygous', 'Homozygous'), ('heterozygous', 'Heterozygous'), ('homozygous-ref', 'Homozygous reference')], max_length=10),
        ),
    ]
