# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180606_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='sequence',
            new_name='alt',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='after',
        ),
        migrations.AddField(
            model_name='variation',
            name='hgvs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='ref',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='variation',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variation',
            name='operation',
            field=models.CharField(choices=[('ins', 'Insertion'), ('del', 'Deletion'), ('insdel', 'Insertion-Deletion'), ('delins', 'Deletion-Insertion'), ('sub', 'Substitution'), ('dup', 'Duplication')], max_length=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='source',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
