# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-08 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181021_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='relationship',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
