# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfile',
            name='name',
            field=models.CharField(default='name', max_length=256),
            preserve_default=False,
        ),
    ]
