# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_wfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WFile')),
            ],
        ),
    ]
