# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_associationrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationrules',
            name='file',
        ),
        migrations.RemoveField(
            model_name='associationrules',
            name='result',
        ),
        migrations.AddField(
            model_name='associationrules',
            name='graph',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='associationrules',
            name='heat_map',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='associationrules',
            name='histogram',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='associationrules',
            name='scatter',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
